### ISSUE TITLE
Review: JS Advanced. Prototype & OOP

### ISSUE THREAD

**Issue by AlekseiIvshin** [ulyanat/epam#2]
Task1 -  1
Task2 - 0

- Надо следовать контракту при переопределении методов (toString & valueOf); 
- Можно вызывать `Parent.apply(this, arguments)` что бы передавать аргументы в родительскую функцию-конструктор;
- Строка 175 - излишняя вложенность

Task3 - 0

- Наследование предполагает, что проверка instanceof со всеми родительскими классами будет возвращать true. Например, `new MonsterTruck() instanceof Vehical -> true`
- Строка 289 - излишняя вложенность

Task4 - 2

**Итоговая оценка 0**

**Comment by ulyanat** [comment]
Task2

- toString & valueOf - переопределила для каждого класса;
- `Parent.apply(this, arguments)` исправила;
- Строка 175 - исправила (в строке 181)

Task3

- Добавила строки: `Bike.prototype = Object.create(Vehical.prototype);
Car.prototype = Object.create(Vehical.prototype);
MonsterTruck.prototype = Object.create(Car.prototype);`
- Строка 289 -  исправила (в строке 298)

**Comment by AlekseiIvshin** [comment]
Task1 - 1
Task2 - 1
Task3 - 1
Task4 - 2

**Итоговая оценка 2**
